# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv",
                    sep='\t')

HTTPError: HTTP Error 429: Too Many Requests

### Step 4. See the first 10 entries

In [ ]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
6,3,1,Side of Chips,NaN,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25

### Step 5. What is the number of observations in the dataset?

In [ ]:
# Solution 1
# Same as excercise 1
chipo.shape[0]

4622

In [ ]:
# Solution 2
# Also works
len(chipo)

4622

### Step 6. What is the number of columns in the dataset?

In [ ]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [ ]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [ ]:
chipo.index
# 0-indexed

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [ ]:
chipo['item_name'].mode()[0]

'Chicken Bowl'

In [ ]:
# or
chipo['item_name'].value_counts().idxmax()

'Chicken Bowl'

### Step 10. For the most-ordered item, how many items were ordered?

In [ ]:
chipo['item_name'].value_counts().max()

726

### Step 11. What was the most ordered item in the choice_description column?

In [ ]:
chipo['choice_description'].value_counts().idxmax()

'[Diet Coke]'

### Step 12. How many items were ordered in total?

In [ ]:
chipo['quantity'].sum()

4972

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [ ]:
chipo['item_price'].dtype

dtype('float64')

#### Step 13.b. Create a lambda function and change the type of item price

In [ ]:
to_float = lambda x: float(x[1:])
chipo['item_price'] = chipo['item_price'].apply(to_float)

TypeError: 'float' object is not subscriptable

#### Step 13.c. Check the item price type

In [ ]:
chipo['item_price'].dtype

dtype('float64')

In [ ]:
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

### Step 14. How much was the revenue for the period in the dataset?

In [ ]:
(chipo['quantity'] * chipo['item_price']).sum()

39237.02

### Step 15. How many orders were made in the period?

In [ ]:
chipo.order_id.value_counts().count()

1834

### Step 16. What is the average revenue amount per order?

In [ ]:
# Solution 1

chipo.groupby('order_id')['item_price'].mean()

In [ ]:
# Solution 2

### Step 17. How many different items are sold?